# Generated by Django 4.2.7 on 2023-11-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "Id_equipment",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("availability", models.BooleanField()),
                ("capacity", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "Country",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("nb_player", models.CharField(max_length=10)),
                ("rank", models.CharField(max_length=20)),
            ],
        ),
    ]
