# Generated by Django 4.2.7 on 2023-11-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="pic_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="flag_url",
            field=models.URLField(blank=True),
        ),
    ]
