# Generated by Django 4.2.7 on 2023-11-07 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_rank_team_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="nb_player",
            new_name="rank",
        ),
    ]
