# Generated by Django 4.2.7 on 2023-11-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_team_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="place",
            field=models.ForeignKey(
                default='Hotel',
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.equipment",
            ),
            preserve_default=False,
        ),
    ]
