# Generated by Django 4.2.7 on 2023-11-07 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_team_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="place",
        ),
    ]
