# Generated by Django 4.2.7 on 2023-11-07 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_rename_place_team_lieu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="lieu",
            new_name="place",
        ),
    ]
