# Generated by Django 4.2.7 on 2023-11-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_rename_lieu_team_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="blog.equipment",
            ),
        ),
    ]
